
project_id = "kpzunjxdvodgprxtqnej"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
image_transformation = {enabled = true}

[edge_runtime]
enabled = true
port = 54325

[functions.handle-social-login]
verify_jwt = false

[functions.validate-nin]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.manage-products]
verify_jwt = true

[functions.upload-image]
verify_jwt = true

[functions.process-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.generate-whatsapp-link]
verify_jwt = false

[functions.browse-products]
verify_jwt = false

[functions.manage-cart]
verify_jwt = false

[functions.checkout]
verify_jwt = false

[functions.track-order]
verify_jwt = false

[functions.submit-feedback]
verify_jwt = false

[functions.update-admin-status]
verify_jwt = true
