// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpzunjxdvodgprxtqnej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwenVuanhkdm9kZ3ByeHRxbmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTM3NDYsImV4cCI6MjA2NDEyOTc0Nn0.yq6THfu3ihEKUjW2_2v0-2Too7Uix_bIxkaVY9m4rcM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);